# Generated by Django 4.2.2 on 2023-07-10 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('app1', '0005_rename_user_id_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(blank=True, max_length=500)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.post')),
                ('commented_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
