# Generated by Django 4.2.2 on 2023-07-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_customuser_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
