# Generated by Django 4.2.2 on 2023-07-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='num_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
